# Generated by Django 5.1.1 on 2024-10-30 17:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_review1"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Review1",
            new_name="ReviewBook",
        ),
    ]
